// Game Variables
let gameseq = []; // Stores the sequence of colors generated by the game
let userseq = []; // Stores the sequence of colors clicked by the user
let btns = ["green", "yellow", "brown", "red"]; // Array of button colors
let started = false; // Flag to check if the game has started
let level = 0; // Keeps track of the current level

// Select H3 for Level Display
let h3 = document.querySelector("h3"); // Selecting the <h3> element to display the level

// Start Game on Key Press
document.addEventListener("keypress", function () {
    if (!started) { // If the game has not started
        started = true; // Set the started flag to true
        levelup(); // Call the function to start the game
    }
});

// Function to Flash Game Sequence Button
function gameflash(btn) {
    btn.classList.add("flash"); // Add 'flash' class to the button
    setTimeout(() => btn.classList.remove("flash"), 250); // Remove 'flash' class after 250ms
}

// Function to Flash User Pressed Button
function userflash(btn) {
    btn.classList.add("userflash"); // Add 'userflash' class to the button
    setTimeout(() => btn.classList.remove("userflash"), 250); // Remove 'userflash' class after 250ms
}

// Function to Level Up
function levelup() {
    userseq = []; // Clear the user's sequence for the new level
    level++; // Increase the level by 1
    h3.innerText = `Level ${level}`; // Update the level text on the screen

    let randIdx = Math.floor(Math.random() * 4); // Generate a random index between 0 and 3
    let randcolor = btns[randIdx]; // Get a random color from the btns array
    let randbtn = document.getElementById(randcolor); // Get the corresponding button element by ID
    
    gameseq.push(randcolor); // Add the random color to the game's sequence
    gameflash(randbtn); // Flash the randomly selected button
}

// Function to Check User Input
function checkans(idx) {
    if (userseq[idx] === gameseq[idx]) { // Check if the user's input matches the game's sequence
        if (userseq.length === gameseq.length) { // If the user has completed the sequence correctly
            setTimeout(levelup, 1000); // Move to the next level after 1 second
        }
    } else { // If the user clicks the wrong button
        h3.innerText = "Game Over! Press any key to restart."; // Display game over message
        document.body.style.backgroundColor = "red"; // Change background color to red
        setTimeout(() => document.body.style.backgroundColor = "white", 200); // Revert background color after 200ms
        reset(); // Reset the game
    }
}

// Function to Handle Button Clicks
function btnpressed() {
    let btn = this; // Get the button that was clicked
    userflash(btn); // Flash the button to show it was clicked
    
    let userColor = btn.getAttribute("id"); // Get the color of the clicked button from its ID
    userseq.push(userColor); // Add the clicked color to the user's sequence
    
    checkans(userseq.length - 1); // Check if the user clicked the correct sequence
}

// Add Event Listeners to Buttons
let allbtns = document.querySelectorAll(".box"); // Select all buttons with class 'box'
allbtns.forEach(btn => btn.addEventListener("click", btnpressed)); // Add click event listener to each button

// Reset Function
function reset() {
    started = false; // Reset the game start flag
    gameseq = []; // Clear the game's sequence
    userseq = []; // Clear the user's sequence
    level = 0; // Reset the level to 0
}